services:
  db:
    image: postgres:17
    container_name: fullstackcrud-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fullstackcrud-server
    restart: always
    ports:
      - "4120:4120"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      NODE_ENV: production
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fullstackcrud-client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  postgres-data:
