services:
  db:
    image: postgres:16
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeinprod!
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4120:4120"
    environment:
      DATABASE_URL: "postgresql://admin:changeinprod!@db:5432/tasks_db?schema=public"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres-data: